In [1]:
#2.3
keras.layers.Dense(512,activation='relu')

NameError: name 'keras' is not defined

In [2]:
output = relu(dot(W,input) + b)

NameError: name 'relu' is not defined

In [3]:
# 2.3.1
def naive_relu(x):
    assert len(x.shape) == 2
    x = x.copy()
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            x[i,j] = max(x[i,j],0)
    return x

In [4]:
def naive_add(x,y):
    assert len(x.shape) == 2
    assert x.shape == y.shape

    x = x.copy()
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            x[i,j] += y[i,j]
    return x

In [5]:
import numpy as np
z = x + y
z = np.maximum(z,0.)

NameError: name 'x' is not defined

In [6]:
#2.3.2
def naive_add_matrix_and_vector(x,y):
    assert len(x.shape) == 2
    assert len(y.shape) == 1
    assert x.shape[1] == y.shape[0]

    x = x.copy()
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            x[i,j] += y[j]
    return x

In [7]:
import numpy as np
x = np.random.random((64,3,32,10))
y = np.random.random((32,10))
z = np.maximum(x,y)

In [8]:
# 2.3.3
import numpy as np
z = np.dot(x,y)

ValueError: shapes (64,3,32,10) and (32,10) not aligned: 10 (dim 3) != 32 (dim 0)

In [9]:
z = x . y

AttributeError: 'numpy.ndarray' object has no attribute 'y'

In [10]:
def naive_vector_dot(x,y):
    assert len(x.shape) == 1
    assert len(y.shape) == 1
    assert x.shape[0] == y.shape[1]
    z = 0
    for i in range(x.shape[0]):
        z += x[i] * y[i]
    return z

In [11]:
import numpy as np

def naive_matrix_vector_dot(x,y):
    assert len(x.shape) == 2
    assert len(y.shape) == 1
    assert x.shape[1] == y.shape[0]

    z = np.zeros(x.shape[0])
    for i in range(x.shape[0]):
        for j in range(x.shape[0]):
            z[i] += x[i,j] * y[j]
    return z

In [12]:
import numpy as np

def naive_matrix_vector_dot(x,y):
    z = np.zeros(x.shape[0])
    for i in range(x.shape[0]):
        z[i] += x[i,j] * y[j]
    return z

In [13]:
import numpy as np

def naive_matrix_vector_dot(x,y):
    assert len(x.shape) == 2
    assert len(y.shape) == 2
    assert x.shape[1] == y.shape[0]

    z = np.zeros((x.shape[0],y.shape[1]))
    for i in range(x.shape[0]):
        for j in range(y.shape[1]):
            row_x = x[i,:]
            column_y = y[:,j]
            z[i,j] = naive_vector_dot(row_x,column_y)
    return z

In [14]:
(a,b,c,d) . (d,) -> (a,b,c)
(a,b,c,d) . (d,e) -> (a,b,c,e)

SyntaxError: invalid syntax (1519975341.py, line 1)

In [16]:
x = np.array([[0.,1.],
              [2.,3.],
              [4.,5.]])
print(x)
x = x.reshape((6,1))
print(x)
x = x.reshape((2,3))
print(x)

[[0. 1.]
 [2. 3.]
 [4. 5.]]
[[0.]
 [1.]
 [2.]
 [3.]
 [4.]
 [5.]]
[[0. 1. 2.]
 [3. 4. 5.]]


In [17]:
x = np.zeros((300,20))
x = np.transpose(x)
print(x)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [ ]:
A = [0.5,1]